### ISSUE TITLE
Signed int

### ISSUE THREAD

**Issue by hannorein** [dtamayo/reboundx#110]
Hi Dan, 

Absolutely not urgent!

Could you check if the `signedint` branch does anything weird on your end. I've been trying to get rid of some of the compiler warnings about comparisons between signed and unsigned ints and in general just make it a bit more consistent. It's not perfect (e.g. N_active is both a flag "-1" and a counter "0, 1, ..."). I think it should be ok, the unit tests pass, but it's easy to introduce a logic error...

Hanno

**Comment by dtamayo** [comment]
Hi Hanno, just ran ~10 ipython_examples on both my macbook pro (M1) and a Ubuntu server workstation and everything seems to be working as expected. Let me know if you'd like me to run any more specific tests!

**Comment by hannorein** [comment]
Thanks a lot Dan! I'll merge it in then.
