### ISSUE TITLE
Failed building editable for reboundx

### ISSUE THREAD

**Issue by Bruntonian** [dtamayo/reboundx#117]
Hi, my name is Ian, I've been getting used to rebound the past couple months and am now trying to go further by modifying some of the reboundx source code for my specific problem. I've never done that before, and am running into what I assume are some basic issues. 

I clone the rebound repository and install no problem. 
However, attempting to clone reboundx and the more complete install outlined in the guide, I keep getting this error: 

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for reboundx
Failed to build reboundx
ERROR: Could not build wheels for reboundx, which is required to install pyproject.toml-based projects
```

I've tried a few different methods to install, such as requesting an older repository (e.g., git checkout c2f976bb) and still no success. I am able to install reboundx via the "quick installation," but I need to be able to edit. 

Any help would be greatly appreciated.

**Comment by dtamayo** [comment]
Hi Ian,

I can't seem to reproduce the error you're having. These problems with library dependencies can be a real pain to debug and track down. virtual environments and conda environments help a lot, are you using either?

Could you try making a fresh virtualenv or conda environment, checking out the rebound and reboundx repos and then 

pip install -e .

in each directory?

**Comment by hannorein** [comment]
I've just tried the exact same commands and everything works for me (Python 3.11.6, macOS Sonoma 14.2). What python version and what operating system are you using?

**Comment by hannorein** [comment]
Just tried it with python 3.12.0 and it also works for me. 🤷‍♂️
