### ISSUE TITLE
"Process finished with exit code 139" when running example code

### ISSUE THREAD

**Issue by Song-XY** [dtamayo/reboundx#123]
Hello there. I create a new conda environment for reboundx and run the example code on the Quick Start Guide
> import rebound
> import reboundx
> sim = rebound.Simulation()
> sim.add(m=1.)
> sim.add(a=1.)
> rebx = reboundx.Extras(sim)

However, I get "`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`".
I'm using Python 3.8, rebound 4.3.2, and reboundx 4.1.0. I tried "`print(reboundx.__githash__); print(rebound.__githash__ )`", and I got `20ae409abea8a47fbfc9c7e8d84c8d559388d95b`, `f81ba52996d6b8642ca25b1931e506bd2bb8faea`
What could be the cause of this problem? Is there a way to fix it? Thanks. )

Best,
-Song

**Comment by dtamayo** [comment]
Thanks Song, that does sound like it could potentially be an issue. What operating system are you using?

**Comment by Song-XY** [comment]
I tried on Linux and macOS 13.6.6, and I got code 139 in both systems.

**Comment by Song-XY** [comment]
Hi Dan, 
I re-install reboundx with `pip install reboundx --no-binary :all:` and it works! The error has been bugging me for days and now I can finally explore reboundx. )  Thank you soooo much!
