### ISSUE TITLE
ReboundX - installing problem with Python

### ISSUE THREAD

**Issue by SimoneR85** [dtamayo/reboundx#125]
Hi.
I'm using rebound to do some speculative research (at the moment). I'd like to improve the calculus using reboundx, but using pycharm,during the installation of reboundx an error follows:

"
> Collecting reboundx==4.0.0
>   Downloading reboundx-4.0.0.tar.gz (91 kB)
>      -------------------------------------- 91.6/91.6 kB 581.3 kB/s eta 0:00:00
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'done'
>   Getting requirements to build wheel: started
>   Getting requirements to build wheel: finished with status 'done'
>   Installing backend dependencies: started
>   Installing backend dependencies: finished with status 'done'
>   Preparing metadata (pyproject.toml): started
>   Preparing metadata (pyproject.toml): finished with status 'done'
> Requirement already satisfied: rebound>=4.0.0 in c:\users\simon\pythonproject\.venv\lib\site-packages (from reboundx==4.0.0) (4.3.2)
> Building wheels for collected packages: reboundx
>   Building wheel for reboundx (pyproject.toml): started
>   Building wheel for reboundx (pyproject.toml): finished with status 'error'
> Failed to build reboundx
> 
>   error: subprocess-exited-with-error
>   
>   Building wheel for reboundx (pyproject.toml) did not run successfully.
>   exit code: 1
>   
>   [24 lines of output]
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-cpython-312
>   creating build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\constants.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\data.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\extras.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\params.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\simulationarchive.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\testing.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\tools.py -> build\lib.win-amd64-cpython-312\reboundx
>   copying reboundx\__init__.py -> build\lib.win-amd64-cpython-312\reboundx
>   running build_ext
>   *** C:\Users\simon\AppData\Local\Temp\pip-build-env-yl03v1tu\overlay\Lib\site-packages\rebound *** C:\Users\simon\pythonProject\.venv\Lib\site-packages/ ***
>   building 'libreboundx' extension
>   creating build\temp.win-amd64-cpython-312
>   creating build\temp.win-amd64-cpython-312\Release
>   creating build\temp.win-amd64-cpython-312\Release\src
>   "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DLIBREBOUNDX -Isrc -IC:\Users\simon\pythonProject\.venv\include -IC:\Users\simon\AppData\Local\Programs\Python\Python312\include -IC:\Users\simon\AppData\Local\Programs\Python\Python312\Include -IC:\Users\simon\AppData\Local\Temp\pip-build-env-yl03v1tu\overlay\Lib\site-packages\rebound "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcsrc/central_force.c /Fobuild\temp.win-amd64-cpython-312\Release\src/central_force.obj -DREBXGITHASH=da728893dc1fb3fd06fa5545d7475190ef9de523 -DLIBREBOUNDX -D_GNU_SOURCE
>   central_force.c
>   src/central_force.c(56): fatal error C1083: Non Š possibile aprire il file inclusione: 'stdlib.h': No such file or directory
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
>   [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for reboundx
> ERROR: Could not build wheels for reboundx, which is required to install pyproject.toml-based projects
> 
> [notice] A new release of pip is available: 23.2.1 -> 24.0
> [notice] To update, run: python.exe -m pip install --upgrade pip

``

I asked to a friend of mine to do the same on his machine. The same error occurs. Do you have any suggestion?

**Comment by dtamayo** [comment]
Hi, it looks like you’re running windows. We hope to add this capability in the future, but REBOUNDx currently only supports Linux and OSX.
