### ISSUE TITLE
problem while installing reboundx

### ISSUE THREAD

**Issue by fredarez** [dtamayo/reboundx#137]
Hi!

I'm trying to install Reboundx via pip install and I get this error in terminal:

 gr_full.c
      src/gr_full.c(63): error C2057: expected constant expression
      src/gr_full.c(63): error C2466: cannot allocate an array of constant size 0
      src/gr_full.c(63): error C2133: 'a_const': unknown size
      src/gr_full.c(185): error C2057: expected constant expression
      src/gr_full.c(185): error C2466: cannot allocate an array of constant size 0
      src/gr_full.c(185): error C2133: 'a_old': unknown size
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for reboundx
Failed to build reboundx

how can I resolve this issue?

Kind regards,

**Comment by dtamayo** [comment]
Hi, it looks like you’re using Windows. Unfortunately REBOUNDx only supports Linux and mac

**Comment by fredarez** [comment]
Ah... ok! I'll run it on my linux machine then?

Are there plans to support windows in the future?


*Frederico Barahona Arez*
