### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by hannorein** [dtamayo/reboundx#16]
I get an error when trying to compile the latest rebounds version due to this line:

https://github.com/dtamayo/reboundx/blob/master/src/rebxtools.c#L143

It is trying to set the `reb_orbit` property `r` which does not exist in the master branch:

https://github.com/hannorein/rebound/blob/master/src/rebound.h#L123

Did we add that to REBOUND at some point? Or am I missing something else?

**Comment by dtamayo** [comment]
Hm…all the examples ‘make’ fine for me.  The line in reboundx.c is for a reb_particle, which does have a .r member.  When we changed orbit.r to orbit.d I changed the corresponding line here: https://github.com/dtamayo/reboundx/blob/master/src/rebxtools.c#L6 <https://github.com/dtamayo/reboundx/blob/master/src/rebxtools.c#L6>.  This is with the latest version of rebound and latest version of reboundx?

**Comment by hannorein** [comment]
What about this line I mentioned above though?

https://github.com/dtamayo/reboundx/blob/master/src/rebxtools.c#L143

**Comment by dtamayo** [comment]
Why isn’t that one OK? The particle structure has a .r member for the particle radius:

https://github.com/hannorein/rebound/blob/master/src/rebound.h#L109 <https://github.com/hannorein/rebound/blob/master/src/rebound.h#L109>

**Comment by hannorein** [comment]
Sorry. This was my fault. All ok now.

**Comment by dtamayo** [comment]
No problem at all.  I appreciate you double-checking things.
