### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by augustfly** [dtamayo/reboundx#18]
We have a manuscript that uses `reboundx` in their analysis. Presently they mention the software by name along with a github URL. This makes it very hard to track its use in systems like google scholar or NASA ADS. 

We would like to know if you have a preferred citation for this code; specifically, a citation that can be put into the list of references for it. 

thanks in advance,

gus muench
data scientist, ApJ/AJ

**Comment by hannorein** [comment]
@dtamayo The best reason to quickly finish up the paper! ;-)

@augustfly I assume there is already a citation to `rebound` (Rein&Liu, Rein&Spiegel, or Rein&Tamayo)?

**Comment by dtamayo** [comment]
Hi @augustfly , as Hanno mentioned, we're working on finishing up the paper.  I think for now the github link is best, since that will not change.  A shame to miss out on the citation though!  Thanks for taking the time to contact us.

**Comment by augustfly** [comment]
@hannorein yep, those citations are in there. 

@dtamayo no problem. if you didn't have a paper in the queue i would have suggested the github=>zenodo route to mint a DOI for the code.
