### ISSUE TITLE
trouble modifying orbital elements directly

### ISSUE THREAD

**Issue by jacobfleisig** [dtamayo/reboundx#22]
Hello,

I am trying to give a test particle a kick in semi-major axis every orbital period by rewriting the "modify_orbits_direct.c" file.  However, although I receive no errors when compiling, the compiling stops and the following appears on the terminal:

'./libreboundx.so: undefined reference to "reb_transformations_inertial_to_jacobi_posvel"
./libreboundx.so: undefined reference to "reb_transformations_jacobi_to_inertial_acc"
./libreboundx.so: undefined reference to "reb_transformations_inertial_to_jacobi_posvelacc"
collect2: error: ld returned 1 exit status
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1 '

I have attached my version of "modify_orbits_direct.c" and a simulation file called "add_forces_test.c" so that you can see the code I am trying to implement.  I think I am not accessing the particles orbital elements in the correct manner??  Thank you for any help you can give!!

![modify_orbits_direct](https://user-images.githubusercontent.com/26045442/29846739-529f4e2e-8cd5-11e7-85f5-f892611f6da4.png)

![add_forces_test](https://user-images.githubusercontent.com/26045442/29846730-44741a1e-8cd5-11e7-90ab-29b70cdabdf8.png)

**Comment by dtamayo** [comment]
Hi Jake,

This sounds like you somehow have an old version of reboundx. Can you update and try again? If you forked the repository, then after committing your changes,

git add remote reboundx https://github.com/dtamayo/reboundx <https://github.com/dtamayo/reboundx>
git fetch reboundx
git merge reboundx/master

**Comment by jacobfleisig** [comment]
Hey Dan,

Thanks for getting back to me so quickly.  I have removed my old reboundx repository, moving my modified 'modify_orbits_direct' file to my desktop, and re-cloned reboundx into my rebound folder.  I moved my modified file back into the repository, replacing your version, and recompiled.  However, I am still getting the same message as before.

**Comment by dtamayo** [comment]
Whoops, the functions it’s bringing up are in rebound/transformations.c. try updating rebound

**Comment by jacobfleisig** [comment]
Everything is compiling now! Thank you so much for the help!
