### ISSUE TITLE
How to compute compute new paramter for each particle

### ISSUE THREAD

**Issue by MilevaE** [dtamayo/reboundx#25]
Hi everyone, 

I was trying to code a module to compute a external force exerted in each particle in the simulation. 
Following the examples is straightforward. However, once the force is computed and the 
new acceleration is given:

```
p->ax += fyork_x
p->ay += fyork_y
p->az += fyork_z
```

 I would like to store, for each particle a new parameter,` f_di `,which is given by the force computed previously times velocity, so something like: 

`
f_di = fyork_x*dvx+fyork_y*dvy+fyork_z*dvx`

any suggestion about how can I do that?

thank you very much!

**Comment by dtamayo** [comment]
Can't type much now, but you can store values by setting them as parameters on particles as shown in the getting started section of the doc

**Comment by MilevaE** [comment]
Hi Dan, 

thanks for your reply =) 

Sorry, but I'm still confuse. Please, if you have some time, could you give some example? 

Don't be worry, and please no pressures at all. Just if you have some time, I don't want to bother you

Thanks in advance! 

best 

mileva

**Comment by dtamayo** [comment]
Hi Mileva,

Here's the C QuickStart guide: [http://reboundx.readthedocs.io/en/latest/c_quickstart.html](http://reboundx.readthedocs.io/en/latest/c_quickstart.html)

It's worth reading all of it (it's short), but specifically starting from "The same goes for a particle" shows you how to store the value on a particle with a specific example. You can just change the name for your needs.

**Comment by MilevaE** [comment]
Thanks Dani!
