### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by hannorein** [dtamayo/reboundx#27]
Right now the reboundx error messages will only appear after the simulation is finished. If it's a long running simulation, that could be a problem. It would be nice to terminate the rebound simulation immediately if there is a serious reboundx error. Example:

```
sim = ...
rebx = reboundx.Extras(sim)
gr = rebx.add("gr_potential")
# gr.params["c"] = constants.C # without this line an error occurs
sim.integrate(1e9) # simulation runs for a long time, error appears at end
```

**Comment by dtamayo** [comment]
Thanks, good point! I guess REBOUNDx needs some way to interrupt without exiting. How does REBOUND deal with this for the reb_errors that formally would have been exit(1)'s?

**Comment by dtamayo** [comment]
Would it make sense for reb_integrate to process messages before starting?

**Comment by hannorein** [comment]
This is a rebound issue, not a reboundx one! Sorry! I've just pushed something to rebound (error_check branch) which should address this. I'll test it for a bit and then merge it in the master branch.
