### ISSUE TITLE
Issue regarding modifying the mass

### ISSUE THREAD

**Issue by freeksdjhfgh** [dtamayo/reboundx#32]
Hi all, I got a bug which intrigued me for several days. I was trying to write and implement two new effects, one is migration and the other one is mass accretion. The migration was implemented as a velocity dependent force, and the mass accretion depended on mass, position of the particle and time as well. It looked like each of them worked well as designed on its own, however, when I tried to combine them together, the integration always quit in the middle and gave a warning message: "Warning! At least 10 predictor corrector loops in IAS15 did not converge..." I checked the orbital output and found out the orbit started to be very unstable after some time. To separate the issue I replace the mass accretion differential with some simple function that only depends on time, namely the logistic function, and it works fine even when combining with the migration effect. Can you give any suggestion about the reason for this problem? Thank you very much.

**Comment by dtamayo** [comment]
Are you implementing the mass accretion as a force or as an operator (post_timestep_modification)? What migration prescription are you using? Typically the latter are forces that orbit average to give a net migration at the desired timescale. If the mass accretion varies around the orbit it's possible you're not getting the orbit-averaged migration effect you expect. This would make sense with your logistic function as long as the timescale you chose for the mass accretion is much longer than the orbit timescale. I would try to output the 'accelerations' from your mass accretion (delta momentum/delta t) and see whether at any point those get comparable to the main gravitational accelerations.

**Comment by freeksdjhfgh** [comment]
Hi thanks for the quick reply. Exactly as you said, I implemented the mass accretion as an operator. For the migration, I am using the template given in REBOUND example folder[(problem.c)](https://github.com/hannorein/rebound/blob/master/examples/planetary_migration/problem.c), however I translated the effect to the REBOUNDx format and introduce some additional parameters. The migration acceleration is characterised by a time scale tau_a. If I shutdown the migration and leave the accretion only, the "acceleration" due to accretion will be specified by the accretion rate only, which is fine; but once I switched on the migration, the coupling between the migration and accretion could blow up some orbital elements and stop the integrator.
If I tried to implement the mass accretion as a force, will it solve the problem? I tried that but it looks it does not work if I just change the declaration in core.c. Does it mean that I have to write the acceleration due to mass accretion by myself?

**Comment by dtamayo** [comment]
Hm, no I don't think you can update the mass in the force calculation self consistently. You should implement it as an operator. Did you check how large the mass accretion accelerations get to see whether they get comparable to the gravitational accelerations from the star? If they do, then all bets are off with typical parametrized migration accelerations. Have you experimented at all with the REBOUNDx implementations of migration (modify_orbits_forces) and mass accretion (modify_mass)?

**Comment by freeksdjhfgh** [comment]
Ok I see. So far I only check one set of parameters. The accretion rate depends on distance and time, and the maximum is only 1e-7 M_solar/yr, so within the distance and mass range it should not exceed the gravitational acceleration; but in the actual simulation it did! Since almost all the parameters involved in the accretion are coupled, it is not trivial to tell directly which part is wrong or causes some hidden "resonance". I will continue checking other parameters and review my code again. I have not used modify_orbit_forces yet, so following your suggestion I will also try to use that template to rewrite the migration and see any difference. Many thanks for your help!

**Comment by freeksdjhfgh** [comment]
Hi I think this problem might be more 'fundamental' than I previously thought. Today I ran the code on linux environment rather than Macintosh, and then it worked perfectly! No halt and no jumping value at all. Then I ran the exact code on Mac and it did not work like before. Besides the difference of OS, the mac uses Intel's i5 and linux desktop uses AMD Ryzen. Do you have any idea of why it happened?

**Comment by hannorein** [comment]
That should not happen! Can you make sure you've recompiled both rebound and reboundx?

**Comment by hannorein** [comment]
Just make sure both rebound and reboundx get recompiled. You can print out the reb_build_str variable to get the date and time of the last compilation. 

If that is not solving the issue, then there is a problem. The could should give the same answer on any machine (down to the last bit). There are multiple reason why this might fail. I am suspicious that this might come from the code that you added (because we tested things like this a lot). But without seeing any code, I can't help much more...

**Comment by freeksdjhfgh** [comment]
It is indeed very strange... I just can't believe that for a language as strict as C such a problem can exist. Luckily this problem is not physical and I can continue working on my project, and I will test it along the way. If there is any new discovery, I will update it here to let you know! Thank you for your kind help.

**Comment by hannorein** [comment]
The way to debug this is by using valgrind. Check for any uninitialized values, overrun array boundaries, or other memory issues.

**Comment by dtamayo** [comment]
Thanks for following up on this thread @hannorein. All moved in (with a lot to unpack), and just set up the wifi!
