### ISSUE TITLE
How to get the radius of a particle when particle mass decreasing using tau_mass

### ISSUE THREAD

**Issue by frakesmart** [dtamayo/reboundx#33]
Hi! I am making a code for my research which requires the sun lose its mass over time. I have used tau_mass to make the sun lose its mass at a certain rate. Now, since the mass have changed, radius and density of the sun should also change. I am wondering if how can I get the radius of the sun (particle) and its density also over period of time. I am confused since I am new to python and reboundx. Thanks for your favorable respose this will help me a lot!

Regards,
Kelvin

**Comment by hannorein** [comment]
Hi Kevin, 

Why do you want to change the radius/density? REBOUND is an N-body integrator and treats the sun as a point particle. The gravitational force from a sphere only depends on the total mass. 

Hanno

**Comment by dtamayo** [comment]
Hi Kelvin, like Hanno said, this is not something REBOUND will help you do, but if you're thinking about the sun's (small) mass loss in its history you can probably just do a simple linearization rather than actually solve for the stellar structure. I'm going to close this for now.
