### ISSUE TITLE
Attribution Error: sim.particles[1].e

### ISSUE THREAD

**Issue by lenun** [dtamayo/reboundx#34]
Hi Dan,

I'm writing a tidal evolution code where I replace the line ``sim.particles[1].m += Mdot*dt`` from Custom_Effects.ipynb with an analogous ``sim.particles[1].e += edot*dt`` (where edot is a constant or could depend on current eccentricity). The program will not let me update eccentricity: I get the error message "AttributeError: can't set attribute." Any suggestions?

Thank you,
Luis

**Comment by dtamayo** [comment]
Hi Luis,

That's right. Internally, REBOUND keeps track of cartesian positions and velocities. So when you say sim.particles[1].e = 0.3, it doesn't know how to make that conversion without all the other orbital elements. One could think about implementing something where setting sim.particles[1].e changes the eccentricity while keeping all the other elements constant, but that's not in there. 

If you want to use this for science, eventually you'll want to write your effect evaluation routine in C. You could look at src/modify_orbits_direct.c in the repo, which is essentially doing what you want to do.

**Comment by lenun** [comment]
Sounds good. Thanks for the fast reply!
