### ISSUE TITLE
python 2.7 OSError: librebound.so

### ISSUE THREAD

**Issue by huhell** [dtamayo/reboundx#42]
Hello,

I have problems importing reboundx, related to previous closed issues. I installed separately rebound (3.10.2) and then reboundx (3.0.4), using pip. On my local machine, everything works just fine with Python 2.7.

However, when I upload all the packages on a cluster, I get the following error messages (still Python 2.7):

`import reboundx`
 ` File "../Py_Libraries/reboundx/__init__.py", line 13, in <module>`
    `clibreboundx = cdll.LoadLibrary(pymodulepath+"/libreboundx"+suffix)`
`  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary`
`    return self._dlltype(name)`
`  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__`
`    self._handle = _dlopen(self._name, mode)`
`OSError: librebound.so: cannot open shared object file: No such file or directory`

Any idea ?

Thanks a lot !

**Comment by huhell** [comment]
One more thing, when I only use REBOUND on the cluster, everything works. The issue pops up with REBOUNDX only.

**Comment by huhell** [comment]
Update: it is now working on the cluster when the REBOUND, REBOUNDX and shared libraries are all located within the folder I am working in.

**Comment by dtamayo** [comment]
Hi, glad you were able to get it working. You shouldn't have to put them all in the same folder, but debugging these path issues can be tricky, especially remotely! I'm happy to help if you want to get it working normally at some point. I'll close the thread for now but feel free to reopen!

**Comment by huhell** [comment]
Alright, thanks again !
