### ISSUE TITLE
Documentation Corrections

### ISSUE THREAD

**Issue by sabaronett** [dtamayo/reboundx#46]
Ambiguous target URL in last paragraph of https://reboundx.readthedocs.io/en/latest/add_effect.html#c-example:
> (See Sec. 2.4 of [OpenGL Keyboard Commands](http://rebound.readthedocs.org/en/latest/c_quickstart.html) for a list of the visualization keyboard commands)

Unable to find possible original source for link thus far.

_4/13/2020 Update_: Resolved in 542f3a490cb25eee8c98561121cbf790db7a6ea0

**Comment by sabaronett** [comment]
Header comment to `examples/modify_mass/problem.c` is identical/taken from `/modify_orbits`.
https://github.com/dtamayo/reboundx/blob/b5e35b4eeed8b6b25978d2f087cb535c8bedbbc8/examples/modify_mass/problem.c#L1-L9

**Comment by sabaronett** [comment]
All standing issues resolved.

Closing.

**Comment by sabaronett** [comment]
@dtamayo, I found some issues on the _readthedocs_ page after #47. I should have compiled and proofread the HTML pages after https://github.com/sabaronett/reboundx/pull/25. Let me know if you'd like me to help fix any of these on a new branch in my fork and submit a PR.

- [ ] https://reboundx.readthedocs.io/en/latest/index.html#attribution
![image](https://user-images.githubusercontent.com/51060809/79251342-de3a8e00-7e34-11ea-9b48-490e70412ed9.png)
- [ ] The following lines appear to be split. https://reboundx.readthedocs.io/en/latest/c_api.html#_CPPv411rebx_timing
![image](https://user-images.githubusercontent.com/51060809/79251993-cc0d1f80-7e35-11ea-9c79-c94d3b0d64eb.png)
- [ ] [`rebx_binary_field_type`](https://reboundx.readthedocs.io/en/latest/c_api.html#_CPPv422rebx_binary_field_type), [`rebx_input_binary_messages`](https://reboundx.readthedocs.io/en/latest/c_api.html#_CPPv426rebx_input_binary_messages), [`rebx_integrator`](https://reboundx.readthedocs.io/en/latest/c_api.html#_CPPv415rebx_integrator), and [`rebx_interpolation_type`](https://reboundx.readthedocs.io/en/latest/c_api.html#_CPPv423rebx_interpolation_type), all appear to list `int` values without their enumerated element names.
![image](https://user-images.githubusercontent.com/51060809/79252090-ec3cde80-7e35-11ea-8431-05f925260522.png)

**Comment by dtamayo** [comment]
Thanks Stanley,

I thought giving an example in latex like people would use would be simpler, though I agree it looks quite ugly :) Happy to be convinced otherwise.

And thanks for catching those others. There's still some work to do on documenting the C code. I'll leave this open to remind myself.

**Comment by jiayindong** [comment]
On the Implemented Effects page, Section 1.1.2 modfiy_orbits_direct, Effect parameter "If p is not set, it defaults to 1." It seems the default p is 0. Feel free to correct me if I'm wrong. Thanks!

**Comment by dtamayo** [comment]
Thanks DJ! Sorry for the slow response--this somehow fell through the cracks. You are absolutely right. I've updated the documentation accordingly
