### ISSUE TITLE
Installing reboundx on fresh Mac Big Sur fails

### ISSUE THREAD

**Issue by jcv109** [dtamayo/reboundx#52]
Dear reboundx creators,
I recently installed rebound on a fresh Mac Big Sur without problems. But, when attempting to install reboundx, the following error appears (in addition to other warnings):
$ pip3 install reboundx
...
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DLIBREBOUNDX -Isrc -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rebound -c src/output.c -o build/temp.macosx-10.9-x86_64-3.9/src/output.o -fstrict-aliasing -O3 -std=c99 -fPIC -Wpointer-arith -DREBXGITHASH=d17670bfad6727c43ce0b74326a1d3d8d61069cd
  src/output.c:217:13: error: implicit declaration of function 'rebx_len' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      int N = rebx_len(list);
              ^
...
Another installation on a fresh Ubuntu 20 run without problems. Hence, I wonder if it could be because a too strict mac-gcc behavior?  Could be fixed in an easy way, without going deep under the hood?. Thanks in advance anyhow for your very interesting packages.

**Comment by hannorein** [comment]
Thanks for letting us know. We already have a fix on this repository: https://github.com/hannorein/reboundx. You can try cloning this repository. We'll merge the fix into the main reboundx repository shortly!

**Comment by hannorein** [comment]
Should be fixed now!
