### ISSUE TITLE
Error Not being thrown when it should

### ISSUE THREAD

**Issue by Rmelikyan** [dtamayo/reboundx#62]
Hi Dan,

I made my first simple force, but the example script didn't seem to actually be connecting to the force code.

I had used the radiation forces code as my template, so I went into the radiation forces (circumplanetary) example file to make sure it was running correctly.

I knew something was off when I saw that p1 and p2 had the same eccentricity values at each time step. Even stranger, is that I went into file and commented out the setting of the speed of light parameter, saved and recompiled, and the output was identical. Not to mention that Rebx should have thrown an error when it tried to integrate without the parameter being set!

(I tested this radiation forces bug in main as well to make sure it wasn't something I introduced in my new branch...)

Any idea what could be going on. Does rad_forces_circumplanetary work correctly for you in C?

Best,
-Robert

**Comment by dtamayo** [comment]
That sounds strange. Yes, rad_force_circumplanetary works correctly for me in C with latest REBOUND and REBOUNDx. Try installing those again in a separate directory and checking whether it does for you. Something seems fishy!

**Comment by dtamayo** [comment]
I'll close this issue for now, but feel free to reopen it if there are any updates!
