### ISSUE TITLE
Problem in installing REBOUND X

### ISSUE THREAD

**Issue by navonilastro** [dtamayo/reboundx#66]
Hi all,
I recently upgraded to a Mac system , I was using REBOUND and REBOUND X in my previous Linux machine. Now, in this new Mac machine I was able to install Rebound successfully and it's running ,but I am somehow not being able to install Rebound X , It always gives me an error message and then terminate the installation whenever I try to install it using "pip install reboundx" . I have attached two Screenshots of the same . Also to just let you know , I have tried this in both my Global as well as Virtual environment , but still Rebound X is not getting installed. 
Previously , I had a conversation with @hannorein , and he suggested me to post the issue here in the forum. 
I would be really thankful to you all if you can help me out with this. 

<img width="1440" alt="Screenshot 2021-06-23 at 12 12 58 PM" src="https://user-images.githubusercontent.com/85501885/123512876-8c7fcb80-d6a7-11eb-988b-c013568a3296.png">
<img width="1440" alt="Screenshot 2021-06-23 at 12 13 15 PM" src="https://user-images.githubusercontent.com/85501885/123512881-91dd1600-d6a7-11eb-974b-aa7506f4c586.png">

**Comment by hannorein** [comment]
Hi Navonil, 

You're screenshots don't show the actual error, just some warnings (which you can ignore). Can you post the actual error message?

Hanno

**Comment by navonilastro** [comment]
Sir, I have tried to post the errors as text. I have also attached the Screenshot showing the error messages.


ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-install-364w_mr9/reboundx_51c0bf23eaa2488c9ab893298ebf2ca6/setup.py'"'"'; __file__='"'"'/private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-install-364w_mr9/reboundx_51c0bf23eaa2488c9ab893298ebf2ca6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-wheel-as3ui8j_
       cwd: /private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-install-364w_mr9/reboundx_51c0bf23eaa2488c9ab893298ebf2ca6/

src/rebxtools.c:77:19: error: implicit declaration of function 'reb_get_com_without_particle' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              com = reb_get_com_without_particle(com, *p);
                    ^
  src/rebxtools.c:77:17: error: assigning to 'struct reb_particle' from incompatible type 'int'
              com = reb_get_com_without_particle(com, *p);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/rebxtools.c:170:19: error: implicit declaration of function 'reb_get_com_without_particle' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              com = reb_get_com_without_particle(com, *p);
                    ^
  src/rebxtools.c:170:17: error: assigning to 'struct reb_particle' from incompatible type 'int'
              com = reb_get_com_without_particle(com, *p);
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 warning and 4 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1



ERROR: Failed building wheel for reboundx







src/rebxtools.c:77:19: error: implicit declaration of function 'reb_get_com_without_particle' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                com = reb_get_com_without_particle(com, *p);
                      ^
    src/rebxtools.c:77:17: error: assigning to 'struct reb_particle' from incompatible type 'int'
                com = reb_get_com_without_particle(com, *p);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/rebxtools.c:170:19: error: implicit declaration of function 'reb_get_com_without_particle' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                com = reb_get_com_without_particle(com, *p);
                      ^
    src/rebxtools.c:170:17: error: assigning to 'struct reb_particle' from incompatible type 'int'
                com = reb_get_com_without_particle(com, *p);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 4 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-install-364w_mr9/reboundx_51c0bf23eaa2488c9ab893298ebf2ca6/setup.py'"'"'; __file__='"'"'/private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-install-364w_mr9/reboundx_51c0bf23eaa2488c9ab893298ebf2ca6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ws/tg_mz9ld1k5cymz491fnh6vm0000gn/T/pip-record-5su17wyc/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/include/python3.9/reboundx Check the logs for full command output.
<img width="1440" alt="Screenshot 2021-06-26 at 6 33 28 PM" src="https://user-images.githubusercontent.com/85501885/123513961-b76d1e00-d6ad-11eb-8b6f-5e2cdb2e1b81.png">
<img width="1440" alt="Screenshot 2021-06-26 at 6 33 51 PM" src="https://user-images.githubusercontent.com/85501885/123513967-bdfb9580-d6ad-11eb-96f6-a3ab95997507.png">

**Comment by dtamayo** [comment]
Thank you for the bug report! I'm back tomorrow and will resolve it. If you
need it immediately you can always install an older version of REBOUND and
REBOUNDx

**Comment by dtamayo** [comment]
Thanks for your patience! The latest commit and latest version on PyPI (3.3.1) is a temporary fix that forces installation of REBOUND 3.16.0 so that things will install. Working on an actual patch now.

**Comment by navonilastro** [comment]
Thank so much you sir. Yes,I could install it for now with the 3.16.0 version . Waiting for the latest version. 

Best,
Navonil

**Comment by dtamayo** [comment]
OK, REBOUNDx 3.4.0 should fix this problem. Could you check whether it does for you? If so, feel free to close the issue

**Comment by navonilastro** [comment]
Yes Sir, thanks a lot it's working now. Thanks for all the help. 
Best,
Navonil
