### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by alekseygenerozov** [dtamayo/reboundx#71]
I was wondering about the following statement in section 6.1 docs: "Note that we should specifically update the passed particles array (NOT sim->particles)." 

What exactly is the issue with doing this? Would updating sim->particles also be an issue for new effects? 

I know this is not an issue per se, so apologies if this is not the right forum.

Thank you!

Aleksey

**Comment by hannorein** [comment]
(@dtamayo should confirm)

This is because some additional computation has to be done to be done for certain coordinate systems. For example, the WHFast integrator can use Jacobi coordinates. If an additional force is applied to one particle, it will also affect other particles.

**Comment by dtamayo** [comment]
Questions always welcome! @hannorein is right as usual :) We sometimes need to evaluate the forces using an arbitrary array of particles and not using the current sim->particles array (e.g., evaluating the forces using particle states at different sub-timesteps in the rk integrator for intermediate calculations )
