### ISSUE TITLE
Python QuickStart Guide

### ISSUE THREAD

**Issue by hannorein** [dtamayo/reboundx#83]
I just needed a quick example to see if REBOUNDx is working, so I looked at the quick start guide. I'm probably just a bit slow, but it took me way too long to remember that I need to add `rebx.add_operator(mm)` if I want to have the modify_mass module actually do anything. Am I missing something or should we add that line to the quick start guide?

**Comment by dtamayo** [comment]
Embarrassing! I added that also removed the unused hashes and changed the mass loss timescale to one that doesn't cause problems with IAS15 so that the QuickStart example doesn't have to get into integrators. Thanks!

**Comment by hannorein** [comment]
Cool! That was fast. That's probably the most important page of the documentation ;-)
